version: 2
project_name: heatdot

builds:
  - id: heatdot-windows
    main: ./cmd/heatdot
    binary: heatdot
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -H=windowsgui

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
